# Generated by Django 3.2 on 2021-05-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210513_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'ordering': ['-completed']},
        ),
    ]
